/**********************************************************************
	Generated by DAZ PreCompiler from the following files:
		curvehair.sl

	Copyright (c) 2002-2020 Daz 3D, Inc - All Rights Reserved.
**********************************************************************/

/*****************************
	Include files
*****************************/
#include "dpcscript.h"

struct DpcScriptItem{
	const char *m_label;
	const char *m_script;
};

static DpcScriptItem s_scriptItems[] = {
	{ "curvehair",
		"////////////////////////////////////////////////////////////////////////////\r\n"
		"// modified version of the maya_fur that ships with 3Delight\r\n"
		"///////////////////////////////////////////////////////////////////////////\r\n"
		"color dz_curve_hair (\r\n"
		"		  vector V;\r\n"
		"		  float Ks;\r\n"
		"		  float roughness;\r\n"
		"		  float Kd;\r\n"
		"	      color basecolor;\r\n"
		"		  color tipcolor;\r\n"
		"		  color specularcolor;\r\n"
		"	     )\r\n"
		"{\r\n"
		"	float sharpness = 1/roughness;\r\n"
		"\r\n"
		"	vector T = normalize (dPdv);\n"
		"    color Cspec=0, Cdiff=0;\n"
		"    float cosang;\n"
		"	normal Nn = normalize(N);\n"
		"	vector Ln, b;\n"
		"	\n"
		"	illuminance( P ) {\n"
		"		Ln = normalize( L );\n"
		"		b = normalize(normalize(Ln^T)^T);\n"
		"		Cdiff += -Ln.b * Cl;\n"
		"		cosang = cos (abs (acos (T.Ln) - acos (-T.V)));\n"
		"		Cspec += pow(cosang, sharpness) * Cl;\n"
		"	}\n"
		"	\n"
		"	Cdiff *= mix(basecolor, tipcolor, v) * Kd;\n"
		"	Cspec *= specularcolor * Ks;\n"
		"	return Cdiff + Cspec;\r\n"
		"}"
	},
	{ 0, 0 } };

/*********************************************************************/
QString getEmbeddedSource( const char *scriptLabel )
{
	DpcScriptItem	*item = s_scriptItems;
	while( item->m_label ){
		if( strcmp( item->m_label, scriptLabel ) == 0 )
			return QString( item->m_script );
		item++;
	};
	return QString();
}

